/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MRowa (https://sketchfab.com/MRowa)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/headphone-e196fbdad6c04f4a8cfd10a4fafd1ca2
Title: Headphone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Headphones = (props) => {
  const { nodes, materials } = useGLTF("/models/headphone.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 159.124, -0.306]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headphone_Characters_0.geometry}
          material={materials.Characters}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headphone_Dynamic_Characters_0.geometry}
          material={materials.Characters}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headphone_Header_Characters_0.geometry}
          material={materials.Characters}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Headphone_Micro_Characters_0.geometry}
          material={materials.Characters}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/headphone.glb");

export default Headphones;
