/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: FreddyAnimator64 (https://sketchfab.com/Danser.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mr-potato-head-56909c8cb27a4de7a4c5273ed13e8a80
Title: Mr Potato Head
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";

const MrPotatoHead = (props) => {
  const targetRef = useRef();
  useGSAP(() => {
    // Animate position (up and down)
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y - 0.5,
      duration: 1.4,
      repeat: -1,
      yoyo: true,
    });
  });
  const { nodes, materials } = useGLTF("/models/mr_potato_head.glb");
  return (
    <group ref={targetRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.5, 1]}>
        <group position={[2.432, -1.849, 6.333]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eyelid_l_eyelid_orange_0.geometry}
            material={materials.eyelid_orange}
            position={[-0.31, 2.153, -6.794]}
          />
        </group>
        <group position={[-1.12, -1.609, 6.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eyelid_r_eyelid_orange_0.geometry}
            material={materials.eyelid_orange}
            position={[1.242, 1.914, -6.89]}
          />
        </group>
        <group position={[0.619, -1.4, 7.534]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eyebrow_l_hat_black_0.geometry}
            material={materials.hat_black}
            position={[-0.497, 1.704, -7.994]}
          />
        </group>
        <group position={[-1.246, -1.173, 7.108]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eyebrow_r_hat_black_0.geometry}
            material={materials.hat_black}
            position={[1.368, 1.477, -7.568]}
          />
        </group>
        <group position={[-1.89, 0.118, 1.246]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.foot_r_blue_0.geometry}
            material={materials.blue}
            position={[2.012, 0.186, -1.706]}
          />
        </group>
        <group position={[1.662, -0.632, 1.246]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.foot_l_blue_0.geometry}
            material={materials.blue}
            position={[-1.54, 0.936, -1.706]}
          />
        </group>
        <group position={[-3.462, 1.479, 2.751]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hand_r_hand_r_0.geometry}
            material={materials.hand_r}
            position={[3.584, -1.175, -3.211]}
          />
        </group>
        <group position={[3.535, -0.096, 2.386]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hand_l_hand_l_0.geometry}
            material={materials.hand_l}
            position={[-3.439, 0.4, -2.847]}
          />
        </group>
        <group position={[3.107, 0.127, 6.109]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ear_l_pink_0.geometry}
            material={materials.pink}
            position={[-0.016, 0.004, 0.006]}
          />
        </group>
        <group position={[-2.858, 0.987, 6.417]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ear_r_pink_0.geometry}
            material={materials.pink}
            position={[2.98, -0.683, -6.878]}
          />
        </group>
        <group position={[-0.118, 0.523, 8.41]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hat_hat_black_0.geometry}
            material={materials.hat_black}
            position={[0.241, -0.219, -8.87]}
          />
        </group>
        <group position={[-0.196, -2.035, 2.756]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mouth_red_0.geometry}
            material={materials.material}
            position={[0.318, 2.339, -3.216]}
          />
        </group>
        <group position={[-0.06, -2.229, 2.905]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mustache_bmustache_lack_0.geometry}
            material={materials.bmustache_lack}
            position={[0.182, 2.533, -3.365]}
          />
        </group>
        <group position={[0.441, -2.149, 5.892]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pupil_l_hat_black_0.geometry}
            material={materials.hat_black}
            position={[-0.001, 0.005, -0.001]}
          />
        </group>
        <group position={[-1.113, -1.974, 5.928]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pupil_r_hat_black_0.geometry}
            material={materials.hat_black}
            position={[0.001, 0.002, -0.001]}
          />
        </group>
        <group position={[-0.526, -2.534, 4.422]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.nose_nose_orange_0.geometry}
            material={materials.nose_orange}
            position={[0.648, 2.838, -4.882]}
          />
        </group>
        <group position={[0.415, -1.898, 5.591]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eye_l_white_0.geometry}
            material={materials.white}
            position={[0.005, 0.01, 0.009]}
          />
        </group>
        <group position={[-1.119, -1.616, 5.652]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.eye_r_white_0.geometry}
            material={materials.white}
            position={[0.007, 0.01, 0.01]}
          />
        </group>
        <group position={[0.051, 0.36, 4.81]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.body_body_orange_0.geometry}
            material={materials.body_orange}
            position={[0.071, -0.056, -5.27]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/mr_potato_head.glb");

export default MrPotatoHead;
